# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregate_across_cells <- function(x, groupings, nthreads) {
    .Call('_demo_aggregate_across_cells', PACKAGE = 'demo', x, groupings, nthreads)
}

